{% set name = "wgpu-native" %}
{% set version = "0.17.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gfx-rs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d84de1dd26295cc0a6fdfc150e3018bda755b7620a1e8950edc96ecb5c2e4eef
  patches:
    - use_prefix.patch

build:
  number: 0
  run_exports:
    # hmaarrfk: 2023/07/29 -- No clue ....
    - {{ pin_subpackage('wgpu-native', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - sysroot_linux-64 2.17  # [linux64]
    - pkg-config
    - clangdev
  host:
    - webgpu-headers
    - clangdev

test:
  commands:
    - test -f ${PREFIX}/lib/libwgpu_native${SHLIB_EXT}   # [unix]
    - test -f ${PREFIX}/include/wgpu.h                   # [unix]
    - if not exist %PREFIX%\\Library\\lib\\wgpu_native.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\wgpu_native.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\wgpu.h exit 1       # [win]

about:
  home: https://github.com/gfx-rs/wgpu-native
  summary: A native WebGPU implementation in Rust, based on wgpu-core.
  description: |
    The bindings are based on the WebGPU-native header found at
    ffi/webgpu-headers/webgpu.h and wgpu-native specific items in ffi/wgpu.h
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE.MIT
    - LICENSE.APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - hmaarrfk
